#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

# this had a wait script for PG
# more info at https://github.com/cookiecutter/cookiecutter-django/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/compose/production/django/entrypoint

exec "$@"
